GET http://localhost:5268

###
GET http://localhost:5268/api/categories/b2e0bb94-75f1-4176-8aaf-abb67ecadb91

###
GET http://localhost:5268/api/categories?searchValue=

###
POST http://localhost:5268/api/categories
Content-Type: application/json

{
    "name" : "Pookie",
    "description" : ""
}


###
PUT  http://localhost:5268/api/categories/cb891cfd-a894-4dd0-a019-e6a18c4b86c4
Content-Type: application/json

{
   // "name" : "pookieeeee",
    "description" : "description of abc"

}



###
DELETE  http://localhost:5268/api/categories/29d1889e-9096-45ea-bfd7-24812fa5f838